### ISSUE TITLE
Obscurity 1.2.X Checklist

### ISSUE THREAD

**Issue by SnowShock35** [SnowShock35/Obscurity#194]
~~**_A more detailed todo list can be found on the Trello board_**~~

- [x] Remove Old Mods
- [x] Add New Mods
- [ ] Redo Configs
- [ ] Redo World Generation
- [ ] Redo HQM
- [ ] Redo Map
- [ ] Test
- [ ] More Testing
- [ ] Even More Testing
- [ ] First Version
